branches:
  - master
repositoryUrl: https://github.com/davidzeng0/mosaic-googlecloud.git
npmPublish: false
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - '@semantic-release/git'
