mongodb:
  url: mongodb://127.0.0.1
oauth:
  accounts.google.com:
    userAgent:
      embedded.setup.v2:
        android: Mozilla/5.0 (Linux; Android 13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36 MinuteMaid
        ios: Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1
  android.googleapis.com:
    deviceInfo: # Google Pixel 2 Sdk 33 Emulator
      imei: '867400022047199'
      otaCert: Q0/9OMpIgVn5SiQ0ZeGRa7F+Uw4=
      id: google/sdk_gphone64_x86_64/emu64x:13/TE1A.220922.012/9302419:userdebug/dev-keys
credentials:
  database: mosaic-credentials