# API services
- name: Android Checkin
  id: android.googleapis.com://checkin
  client: google.rest # Name of client used to make API calls
  endpoints:
    - host: android.googleapis.com
      transport:
        - application/json
        - application/x-protobuffer
    - host: device-provisioning.googleapis.com
      transport:
        - application/json
        - application/x-protobuffer
  implementation: '@protos/google/android/gsf/checkin/android_checkin.AndroidCheckinDefinition' # protobuf service implementation

- name: Android Authentication
  id: android.googleapis.com://auth
  client: google.android.auth
  endpoints:
    - host: android.googleapis.com
      transport:
        - googleauth
  methods:
    - name: Auth
      method: POST
      path: /auth
      transport:
        - googleauth